server.port=8080
spring.application.name=reservation-web

# Database configuration (same as backend)
# These will be overridden by Docker environment variables
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/client_reservation}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:lin_ux}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1997}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
#spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.show-sql=true
