# These will be overridden by Docker environment variables
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/client_reservation}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:lin_ux}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1997}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
#spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.show-sql=true

spring.main.web-application-type=none

server.port=8080

# CORS configuration for Docker
#spring.web.cors.allowed-origins=http://localhost:3000,http://localhost:80
#spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#spring.web.cors.allowed-headers=*
#spring.web.cors.allow-credentials=true